### ISSUE TITLE
Cardio Recovery must insert an excerside

### ISSUE THREAD

**Issue by jjtbsomhorst** [Wassup789/garmin-connect-enhancements#4]
### Description

When creating a cardio / strength workout this extension expects me to fill in an exercise for the recovery phase. This is odd because this phase is used to rest for a few minutes/seconds.

### Reproduction steps

1. Create a new strength workout
2. Add a recursion ( don't know the correct english translation )
3. Add a workout step
4. Open the recovery step and see that the exercise step field is required.. 

### Which platform did you discover this bug?

Firefox Add-ons

### Please provide the environment you discovered this bug

```true
Firefox 133.0.3 (64-bit)
Ubuntu 24
```

**Comment by Wassup789** [comment]
Unless I am mistaken, this looks to be expected behaviour. In Garmin Connect, the recovery step always involved an exercise (I believe they expect it to be used for post-workout stretches, yoga, etc.).
Changing the step type to "Rest" seems to do what you want (resting for a short period with no exercise).

**Comment by jjtbsomhorst** [comment]
Hi @Wassup789. I think you are right. When I disable the extension it works the same. My bad.
